my_proj/src/medicinepredictor/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^process/',views.process,name="process"),
    url(r'^', TemplateView.as_view(template_name= "medicinepredictor/medicinepredictor.html"), name="medicinepredictor"),
    ]

my_proj/src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import symptomchecker.urls
import finddoctor.urls
import medicinepredictor.urls
import healthtips.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^symptomchecker/', include(symptomchecker.urls, namespace='symptomchecker')),
    url(r'^finddoctor/', include(finddoctor.urls, namespace='finddoctor')),
    url(r'^medicinepredictor/', include(medicinepredictor.urls, namespace='medicinepredictor')),
    url(r'^healthtips/', include(healthtips.urls, namespace='healthtips'))
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_proj/src/medicinepredictor/models.py
from django.db import models

# Create your models here.

my_proj/src/medicinepredictor/forms.py
from django import forms 
from django.forms import ModelForm, CharField, TextInput , ChoiceField


GENDER=[('1','male'),
         ('0','female')]

CHEST = [
    ('1', 'typicalAngina'),
    ('2', 'atypicalAngina'),
    ('3', 'nonAnginalPain'),
    ('4', 'asymptomatic')]

RESTECG = [
    ('0', 'normal'),
    ('1', 'having ST-T wave abnormality'),
    ('2', 'non-showing probable or definite left ventricular hypertrophy ')]

SLOPE = [
    ('1', 'upsloping'),
    ('2', 'flat'),
    ('3', 'downsloping')
    ]
    

EXANG=[('1','yes'),
         ('0','no')]  
   
class HeartForm(forms.Form):
    age = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    
    gender= forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect())
    chestpaintype = forms.ChoiceField(choices=CHEST, widget=forms.RadioSelect())
    bp = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    chol = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    bsugar= forms.CharField( widget=TextInput(attrs={'type':'number'}))
    thalach = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    #exang= forms.CharField( widget=TextInput(attrs={'type':'number'}))
    exang=forms.ChoiceField(choices=EXANG, widget=forms.RadioSelect())
    oldpeak = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    ca = forms.CharField( widget=TextInput(attrs={'type':'number'}))
    restecg= forms.ChoiceField(choices=RESTECG, widget=forms.RadioSelect())
    slope= forms.ChoiceField(choices=SLOPE, widget=forms.RadioSelect())
    

my_proj/src/medicinepredictor/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.views.generic import TemplateView
from django.contrib.sessions.models import Session
#from django.views.generic.edit import ProcessFormView
import logging
from nltk.corpus import stopwords
#from app.models import 
from django.db import connection,transaction
from collections import OrderedDict
from .forms import HeartForm
import csv
import subprocess
# Create your views here.


def process(request):
    text="wrong"
    z="1"
    output=0   
    final=[]
    if request.method == 'POST':
        
        myform = HeartForm(request.POST)
        print("hi")
        #print ("****RR*****")
        #output=subprocess.check_call(['Rscript', '/home/admin-pc/Hospital-Home/sample.R'], shell=False)
        #print("****R***")
        if myform.is_valid():
            
            print("hello")
            age=myform.cleaned_data['age']
            sex=myform.cleaned_data['gender']
            cp=myform.cleaned_data['chestpaintype']
            bp=myform.cleaned_data['bp']
            chol=myform.cleaned_data['chol']
            bsugar=myform.cleaned_data['bsugar']
            thalach=myform.cleaned_data['thalach']
            exang=myform.cleaned_data['exang']
            oldpeak=myform.cleaned_data['oldpeak']
            ca=myform.cleaned_data['ca']
            restecg=myform.cleaned_data['restecg']
            slope=myform.cleaned_data['slope']
            out_file=open('/home/admin-pc/Hospital-Home/testHeart.csv','w')
            file=csv.writer(out_file)

            final=[age,sex,cp,bp,chol,bsugar,restecg,thalach,exang,oldpeak,slope,ca]
            print(final)
            file.writerow(final)
            out_file.close()
            print ("****RR*****")
            output=subprocess.check_output(['Rscript', '/home/admin-pc/Hospital-Home/sample.R'], shell=False)
            print("****R***")

    return render(request, 'medicinepredictor/medicinepredictor.html', {'form':final,'output':output})

my_proj/src/medicinepredictor/templates/medicinepredictor/medicinepredictor.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Medicine Predictor</title>
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Varela+Round" rel="stylesheet"/>
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
<link rel="stylesheet" href="{% static 'materialize/css/default2.css' %}" >
<link rel="stylesheet" href="{% static 'materialize/css/fonts.css' %}" >
<link rel="stylesheet" href="{% static 'materialize/css/style.css' %}" >
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  

<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
      <script> $(document).ready(function() {
  $('.modal-trigger').leanModal();
});  
$(document).ready(function() {
    $('select').material_select();
});

      </script>
<div id="wrapper">
  <div id="page-wrapper">
    <div id="page">
      <div id="wide-content" >
  
  
          <div class="row">
            
          <div class="col s1 m4" >
        <p><br><img src="{% static 'site/img/healthtip.png' %}" alt="" width="200" height="200" class="alignleft" /> </p>
          </div>
        
        
          <form action="{% url "medicinepredictor:process" %}" method="POST">
                    {% csrf_token %}
          <div class="input-field col s1 m5">
          <h3>Heart Disease<b style="color:#069">Predictor</b></h3>
          {{output}}
          </div></div>
          <div class="row">
            <div class="input-field col s1 m5">
                   <b>AGE</b><input name="age" type="number" min="0" max="120" class="validate" style="border: 1px solid black" >
                   </div>
                   </div> 
                   <div class="row">
                    <div class="input-field col s1 m2">

      <b>GENDER</b><input name="gender" type="radio" value="0" id="male" />
      <label for="male">male</label>
      <br>
    </div>
      <div class="input-field col s1 m2">
      <input name="gender" type="radio" value="1" id="female" />
      <label for="female">female</label><br> <br> <br> <br>
      </div>
       </div>
       <div class="row">
                    <div class="input-field col s1 m5">
      <b>CHEST PAIN TYPE</b> <br>
      <input name="chestpaintype" type="radio" value="1" id="typicalAngina" />
      <label for="typicalAngina">typicalAngina</label>
      <br>
           
      <input name="chestpaintype" type="radio" value="2" id="ata" />
      <label for="ata">atypicalAngina</label><br> 

       <input name="chestpaintype" type="radio" value="3" id="nap" />
      <label for="nap">nonAnginalPain</label><br> 

       <input name="chestpaintype" type="radio" value="4" id="asm" />
      <label for="asm">asymptomatic</label><br> 
      </div>
       </div>

         <!--
          <div class="row">
         <div class="input-field col s1 m5">
          chestpaintype
           <select name="chestpaintype">
      
      <option value="1">typical angina</option>
      <option value="2">atypical angina</option>
      <option value="3">non-anginal pain</option>
      <option value="4">asymptomatic</option>
    </select>
 </div></div>
 -->
 <div class="row">

 <div class="input-field col s1 m5">
             <b>resting blood pressure (in mm Hg)</b><input name="bp" type="number" min="0" max="350" class="validate" style="border: 1px solid black" >  
           </div>
              </div>
              
              <div class="row">

 <div class="input-field col s1 m5">
             <b>chol: serum cholestoral in mg/dl </b><input name="chol" type="number" min="0"  class="validate" style="border: 1px solid black" >  
           </div>
              </div>

              <div class="row">

 <div class="input-field col s1 m5">
             <b> (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false) </b><input name="bsugar" type="number" min="0" max="1" class="validate" style="border: 1px solid black" >  
           </div>
              </div>
<div class="row">

 
               <div class="row">

 <div class="input-field col s1 m5">
             <b> maximum heart rate achieved  </b><input name="thalach" type="number" class="validate" style="border: 1px solid black" >  
           </div>
              </div>
              <div class="row">
<div class="input-field col s1 m5">
             <b>Exercise Induced Angina:</b><br>
             <input name="exang" type="radio" value="1" id="yes" />
      <label for="yes">yes</label>
      <br>
           
      <input name="exang" type="radio" value="0" id="no" />
      <label for="no">no</label>
           </div>
              </div>
             <div class="row">

 <div class="input-field col s1 m5">
             <b> Old Peak ( ST depression induced by exercise relative to rest ) </b><input name="oldpeak" type="number"  class="validate" style="border: 1px solid black" >  
           </div>
              </div>

              <div class="row">

 <div class="input-field col s1 m5">
             <b> number of major vessels (0-3) colored by flourosopy  </b><input name="ca" type="number" min="0" max="3" class="validate" style="border: 1px solid black" >  
           </div>
              </div>

<div class="row">
<div class="input-field col s1 m5">
             <b>Rest ECG:</b><br>
             <input name="restecg" type="radio" value="0" id="normal" />
      <label for="normal">normal</label>
      <br>
           
      <input name="restecg" type="radio" value="1" id="waveabnormality" />
      <label for="waveabnormality">having ST-T wave abnormality</label>
      <br>
      <input name="restecg" type="radio" value="2" id="hypertrophy" />
      <label for="hypertrophy">non-showing probable or definite left ventricular hypertrophy </label>
      <br>
           </div>
              </div>
      <div class="row">
<div class="input-field col s1 m5">
             <b>Slope:</b><br>
             <input name="slope" type="radio" value="1" id="upsloping" />
      <label for="upsloping">upsloping</label>
      <br>
           
      <input name="slope" type="radio" value="2" id="flat" />
      <label for="flat">flat</label>
      <br>
      <input name="slope" type="radio" value="3" id="downsloping" />
      <label for="downsloping">downsloping</label>
      <br>
           </div>
              </div>
        <!--      
        <div class="row">
         <div class="input-field col s1 m5">
          
           <select name="rest_ecg">
      <option value="" disabled selected>Rest ECG</option>
      <option value="0">  normal </option>
      <option value="1"> having ST-T wave abnormality</option>
      <option value="2">non-showing probable or definite left ventricular hypertrophy </option>
      
    </select>
 </div></div>
-->
 

<!--
               <div class="row">

 <div class="input-field col s1 m5">
             <b>Exercise Induced Angina:</b><br>
             <input name="exang" type="radio" value="1" id="yes" />
      <label for="yes">yes</label>
      <br>
           
      <input name="exang" type="radio" value="0" id="no" />
      <label for="no">no</label>
           </div>
              </div>
               <div class="row">

 <div class="input-field col s1 m5">
             <b> Old Peak </b><input name="oldpeak" type="number"  class="validate" style="border: 1px solid black" >  
           </div>
              </div>
              <div class="row">
         <div class="input-field col s1 m5">
          
           <select name="slope">
      <option value="" disabled selected>The slope of the peak exercise ST segment </option>
      <option value="1">  upsloping </option>
      <option value="2"> flat</option>
      <option value="3">down-sloping</option>
      
    </select>
 </div></div>
 <div class="row">

 <div class="input-field col s1 m5">
             <b> number of major vessels (0-3) colored by flourosopy  </b><input name="ca" type="number" min="0" max="3" class="validate" style="border: 1px solid black" >  
           </div>
              </div>

                <div class="row">
         <div class="input-field col s1 m5">
          
           <select name="thal">
      <option value="" disabled selected>thal </option>
      <option value="3">  normal </option>
      <option value="6"> fixed defect </option>
      <option value="7"> reversible defect</option>
      
    </select>
 </div></div> -->
            <br> <br> <br>
                 <div class="col s1 m1">
                
         <button class="btn waves-effect waves-light light-blue darken-3" type="submit" name="action">Go
                 </button>

                 </div>
                  </form>
                </div>
                  
  <div class="row">
  <br><br><br><br>
    <div class="col s12 m6">
        <h5 class="black-text"> Get your medicines </h4>
        <span class="blue-text"><br>Get prescribed medicines including suggested alternatives for a safe treatment and cure. 
          </span>
        </div>
        <div class="col s12 m6">
          <h5 class="black-text"> Learn About Possible Causes </h4>
          <span class="blue-text"><br>Get a better understanding of a condition: Discover if you're at risk, how it's diagnosed, and what you can do about it.
          </span>
      </div>
    </div>
    <br><br>
        <div class="row">    
    
      <a class="modal-trigger" href="#modal1"> <h6 class="black-text"><b style="color:#069;padding-left:10px" >List of most common disorders and conditions</b> </h6> </a>
      <br> 
            <a class="modal-trigger" href="#modal2"> <h6 class="black-text"><b style="color:#069;padding-left:10px" > List of body locations/systems</b> </h6> </a>
    </div>
           
    
            
      </div>
    

  
    

  </div>
</div>
</body>
</html>