my_proj/src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import symptomchecker.urls
import finddoctor.urls
import medicinepredictor.urls
import healthtips.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^symptomchecker/', include(symptomchecker.urls, namespace='symptomchecker')),
    url(r'^finddoctor/', include(finddoctor.urls, namespace='finddoctor')),
    url(r'^medicinepredictor/', include(medicinepredictor.urls, namespace='medicinepredictor')),
    url(r'^healthtips/', include(healthtips.urls, namespace='healthtips'))
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_proj/src/symptomchecker/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
#from django.views.generic.edit import ProcessFormView
from . import views

urlpatterns = [
    url(r'^process/',views.process,name="process"),
    url(r'^', TemplateView.as_view(template_name= "symptomchecker/symptomchecker.html"), name="symptomchecker"),
    ]

my_proj/src/symptomchecker/forms.py
from django import forms

class SymptomForm(forms.Form):
    symptom_text = forms.CharField(max_length=100)

my_proj/src/symptomchecker/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import SymptomForm
from django.views.generic import TemplateView
from django.contrib.sessions.models import Session
#from django.views.generic.edit import ProcessFormView
import logging
from nltk.corpus import stopwords
#from app.models import 
from django.db import connection,transaction
from collections import OrderedDict
import time
from django.core.mail import send_mail
from operator import itemgetter
# Create your views here.


#conn1=mysql.connector.connect(user='root', password='1234',database='hospitalHome')   
    #form_class = forms.SymptomForm

cur=connection.cursor()
doctors=[]
def fillDoctors(key_bodyloc,proportion):
    bodyloc_specialty_query="select distinct Speciality from body_speciality where body_location in (%s) "
    #cur.execute(bodyloc_specialty_query)
    data1=([key_bodyloc])
    #print(bodyloc_specialty_query,data)
    cur.execute(bodyloc_specialty_query,data1)
    results=cur.fetchall()
    specialities=[x[0] for x in results]
    #condition=""
    #for speciality in specialities:
     #   print(str(speciality))
      #  y=speciality.strip()
       # condition=condition+"'%"+y+"%'"+" or Speciality like "
    #print(speciality)
    #print(condition)
    #like = "Speciality LIKE %%%s%%"
    #condition = like + (" OR {}".format(like)) * len(specialities-1)
    #specialty_doctors_query="select DoctorName,Speciality,ClinicName from Doctors where Speciality like %s limit %s"
    #query = "select DoctorName,Speciality,ClinicName from Doctors where %s LIMIT %s ",(condition,proportion)
    #query2="select DoctorName,Speciality,ClinicName from Doctors where Speciality IN %s LIMIT %s "
    query2="select distinct dc.DoctorName,ds.Speciality,dc.ClinicName,ca.Address from doc_speciality as ds,doc_clinic as dc,clinic_add as ca where (ds.DoctorName=dc.DoctorName AND dc.ClinicName=ca.ClinicName AND ds.Speciality IN %s) LIMIT %s "
    #data2=([condition,proportion])
    #print(specialty_doctors_query)
    #cur.execute(specialty_doctors_query,data2)
    #cur.execute(query,specialities)
    data3=([specialities,proportion])
    #print(data3)
    cur.execute(query2,data3)
    final=cur.fetchall()
    #print(final)
    #print(results)
    print(final)
    for row in final:
      doctors.append(row)

def process(request):
    text="wrong"
    rows=[]
    diseasetable=[]
    
    aboutDisease=[]
    twolists=[]
    unique_data=[]
    final=[]
    if request.method == 'POST':
        myform = SymptomForm(request.POST)
        if myform.is_valid():
            #print (request.session.session_key)
            


        #user = User.objects.get(pk=uid)
            #print(uid)
        #print (user.username, user.get_full_name(), user.email)
            text=myform.cleaned_data['symptom_text']
            stop = set(stopwords.words('english'))
            stop = stop | {'feel','like','frequently'}
            print(stop)

            important_words=[]
            for i in text.lower().split():
              if i not in stop:
                important_words.append(i)

            for i in range(0,len(important_words)):
                print (important_words[i])

            #cur=conn.cursor()
            
            query="select distinct D.Disease as disease, D.BodyLocation as body_location, X.rank as rank , D.Symptoms from DiseaseSymptoms D join ( select T.disease_id, sum(T.norm_tfidf) as rank from (select disease_id, norm_tfidf from norm_symptoms_tfidf where term in %s )T group by T.disease_id order by sum(T.norm_tfidf) desc) X on X.disease_id=D.DiseaseID order by X.rank desc limit 10" % repr(important_words).replace('[','(').replace(']',')') 
            cur.execute(query)
            #transaction.commit_unless_managed()
            rows = cur.fetchall()
            #print(type(row))
            #print (rows)
            for row in rows:
                diseasetable.append([row[0],row[1],row[2]])
                aboutDisease.append(row[3])

            #print("disease table ")
            top2diseases=diseasetable[0][0]+"|"+diseasetable[1][0]
            querytime=time.strftime("%H:%M:%S")
            querydate=time.strftime("%d/%m/%Y")
            if(request.session.session_key!=None):
             session = Session.objects.get(session_key=request.session.session_key)
             history_query="select * from history where id=%s"

             uid = session.get_decoded().get('_auth_user_id')
             cur.execute(history_query,uid)
             history=cur.fetchall()
             print(history)
             name_query="select name,email from authtools_user where id=%s"
             cur.execute(name_query,uid)
             results=cur.fetchall()
             name=results[0][0]
             email= results[0][1]
             data4=([uid,top2diseases,querydate,querytime])
             q="insert into history values(%s,%s,%s,%s)"
             cur.execute(q,data4)
             diseaseText="These are the descriptions of diseases you possibly have"
             i=1
             for d in aboutDisease:
                diseaseText=diseaseText+"\n"+str(i)+d+"\n"
                i=i+1
             send_mail('hospital@home symptom checker', diseaseText, 'namratha8a@example.com', [email], fail_silently=False)

            print(diseasetable)
            bodyloc={}
            total_body_locs=0
            for i in range(0,len(rows)):
                bl=diseasetable[i][1]
                print(bl)
                if bl==None:
                    break
                if bodyloc.get(bl):
                    bodyloc[bl]=bodyloc[bl]+1
                else:
                    bodyloc[bl]=1

                total_body_locs=total_body_locs+1

            proportion=0
            temp=sorted(bodyloc.items(), key=lambda x: (-x[1], x[0]))
            bodyloc = dict(temp)
            print(temp)
            #print(total_body_locs)
            #print(bodyloc)
            #for key in bodyloc:
             #   proportion=int(float(bodyloc[key])/total_body_locs*10)
                #print(proportion)
              #  doctors=fillDoctors(key,proportion)

            for item in temp:
                proportion=int(float(item[1])/total_body_locs*10)
                #print(proportion)
                fillDoctors(item[0],proportion)
            #cur.close()
            twolists=zip(diseasetable,aboutDisease)
            temp=[]
            for row,ad in twolists:
              temp.append([row[0],ad])
            unique_data = [list(x) for x in set(tuple(x) for x in temp)]
            final=[]
            for y in unique_data:
              for z in diseasetable:
                if(z[0]==y[0]):
                  final.append([y[0],y[1],z[2]])
                  break
            final=sorted(final,key=itemgetter(2),reverse=True)
    return render(request, 'symptomchecker/symptomchecker.html', {'rows':diseasetable,'form':text,'doctors':doctors,'twolists':twolists,'unique_data':final})


   

my_proj/src/symptomchecker/templates/symptomchecker/symptomchecker.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Symptom-Checker</title>
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Varela+Round" rel="stylesheet"/>
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
<link rel="stylesheet" href="{% static 'materialize/css/default2.css' %}" >
<link rel="stylesheet" href="{% static 'materialize/css/fonts.css' %}" >
<link rel="stylesheet" href="{% static 'materialize/css/style.css' %}" >
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  

<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
      <script> $(document).ready(function() {
  $('.modal-trigger').leanModal();
});  </script>
<div id="wrapper">
	<div id="page-wrapper">
		<div id="page">
			<div id="wide-content" >
  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
     <div class="row">
     	<div class="col s1 m10">
     <h4 class=black-text> Disorders and Conditions </h4>
 </div>
   <div class="col s1 m2">
 <a href="#!" class=" modal-action modal-close waves-effect btn">X</a>
</div>
</div>
    <p class="blue-text text-darken-3" >Cancers</p>
    <p class="blue-text text-darken-3" >Diabetes Mellitus</p>
    <p class="blue-text text-darken-3" >Genetics/Birth Defects</p>
    <p class="blue-text text-darken-3" >Infections</p>
    <p class="blue-text text-darken-3" >Injuries and Wounds</p>
    <p class="blue-text text-darken-3" >Mental Health and Behavior</p>
    <p class="blue-text text-darken-3" >Metabolic Problems</p>
    <p class="blue-text text-darken-3" >Poisoning, Toxicology, Environmental Health</p>
    <p class="blue-text text-darken-3" >Pregnancy and Reproduction</p>
    <p class="blue-text text-darken-3" >Substance Abuse Problems</p>


    </div>
    
  </div>
   <div id="modal2" class="modal">
    <div class="modal-content">
     <div class="row">
     	<div class="col s1 m10">
     <h4 class=black-text> Body Locations/Systems </h4>
 </div>
   <div class="col s1 m2">
 <a href="#!" class=" modal-action modal-close waves-effect btn">X</a>
</div>
</div>
    <p class="blue-text text-darken-3" >Blood, Heart and Circulation</p>
    <p class="blue-text text-darken-3" >Bones, Joints and Muscles</p>
    <p class="blue-text text-darken-3" >Brains and Nerves</p>
    <p class="blue-text text-darken-3" >Digestive System</p>
    <p class="blue-text text-darken-3" >Ear,Nose and Throat</p>
    <p class="blue-text text-darken-3" >Endocrine System</p>
    <p class="blue-text text-darken-3" >Eyes and Vision</p>
    <p class="blue-text text-darken-3" >Immune System</p>
    <p class="blue-text text-darken-3" >Kidneys and Urinary System</p>
    <p class="blue-text text-darken-3" >Lungs and Breathing</p>
    <p class="blue-text text-darken-3" >Mouth and Teeth</p>
    <p class="blue-text text-darken-3" >Skin, Hair and Nails</p>
    <p class="blue-text text-darken-3" >Male Reproductive System</p> 
    <p class="blue-text text-darken-3" >Female Reproductive System</p>  
    </div>
    
  </div>
  				<div class="row">
    				
  				<div class="col s1 m4" >
				<p><br><img src="{% static 'site/img/symptom.jpeg' %}" alt="" width="200" height="200" class="alignleft" /> </p>
			    </div>
			    <div class="input-field col s1 m5">
					<h3>Symptom<b style="color:#069">Checker</b></h3>
					<p> Experiencing symptoms but not sure what they mean?
Use our Symptom Checker to help determine possible causes and treatments, and when to see a doctor. </p>
                   <form action="{% url "symptomchecker:process" %}" method="POST">
                    {% csrf_token %}
                    
                   <input id="symptomquery" type="search" class="validate" style="border: 1px solid black" name="symptom_text" >
                   <label for="symptom_text"></label>
                </div>
                 <div class="col s1 m1">
                 <br><br><br><br><br><br><br><br><br><br>
 				 <button class="btn waves-effect waves-light light-blue darken-3" type="submit" name="action">Go
                 </button>
                 
                
                 </div>
                 
                </div>
                <!--{% for row,ad in twolists%}
                <div class="divider"></div>
                <div class="section">
                <h5>{{row.0}}</h5>
                <p>{{ad}}</p>
                </div>
                {% endfor %}-->
                {% for x in unique_data%}
                <div class="divider"></div>
                <div class="section">
                <h5>{{x.0}} <span style="float:right">{{x.2}}</span> </h5>
                <p>{{x.1}}</p>
                </div>
                {% endfor %}
                
				
				
	<div class="row">
	<br><br><br><br>
    <div class="col s12 m6">
        <h5 class="black-text"> Assess your Symptoms </h4>
        <span class="blue-text"><br>Want to know what's causing your aches, pain, or rashes? We can identify conditions related to your symptoms.
          </span>
        </div>
        <div class="col s12 m6">
        	<h5 class="black-text"> Learn About Possible Causes </h4>
        	<span class="blue-text"><br>Get a better understanding of a condition: Discover if you're at risk, how it's diagnosed, and what you can do about it.
          </span>
      </div>
    </div>
    <br><br>
        <div class="row">    
		
			<a class="modal-trigger" href="#modal1"> <h6 class="black-text"><b style="color:#069;padding-left:10px" >List of most common disorders and conditions</b> </h6> </a>
			<br> 
            <a class="modal-trigger" href="#modal2"> <h6 class="black-text"><b style="color:#069;padding-left:10px" > List of body locations/systems</b> </h6> </a>
		</div>
    <div id="modal3" class="modal">
    <div class="modal-content">
     <div class="row">
      <div class="col s1 m10">
     <h4 class=black-text> Recommended Doctors </h4>
 </div>
   <div class="col s1 m2">
 <a href="#!" class=" modal-action modal-close waves-effect btn">X</a>
</div>



      <table>
        <thead>
          <tr>
              <th data-field="id">Doctor Name</th>
              <th data-field="name">Speciality</th>
              <th data-field="price">Clinic Name</th>
              <th data-field="price">Address</th>
          </tr>
        </thead>

        <tbody>
          {% for doctor in doctors %}
          <tr>
            <td>{{doctor.0}}</td>
            <td>{{doctor.1}}</td>
             <td>{{doctor.2}}</td>
              <td>{{doctor.3}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
            


</div>
    


    </div>
    
  </div>
       <a class="modal-trigger waves-effect waves-light light-blue darken-3 btn " href="#modal3">Get Doctors for your symptoms</a>         
			</div>
		
</form> 
	
		

	</div>
</div>

</body>
</html>