my_proj/src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    
]

my_proj/src/finddoctor/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
	url(r'^process/',views.process,name="process"),
    url(r'^', TemplateView.as_view(template_name= "finddoctor/finddoctor.html"), name="finddoctor"),
    #url(r'^',views.display,name="finddoctor"),

    ]

my_proj/src/healthtips/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
   # url(r'^', TemplateView.as_view(template_name= "healthtips/healthtips.html"), name="healthtips"),
    url(r'^',views.display,name="healthtips")
    ]

my_proj/src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import symptomchecker.urls
import finddoctor.urls
import medicinepredictor.urls
import healthtips.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^symptomchecker/', include(symptomchecker.urls, namespace='symptomchecker')),
    url(r'^finddoctor/', include(finddoctor.urls, namespace='finddoctor')),
    url(r'^medicinepredictor/', include(medicinepredictor.urls, namespace='medicinepredictor')),
    url(r'^healthtips/', include(healthtips.urls, namespace='healthtips'))
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_proj/src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

my_proj/src/templates/_brandname.html
hospital@home

my_proj/src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About Us</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">Contact Us</a></li>

my_proj/src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page" style="height:800px;">
  <div class="container">
    
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">Healthcare that Cares</p>
      </div>
    
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead"></p>
      </div>
    </div>
  
    </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

my_proj/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'  type='text/css'>

      <!--Import materialize.css-->
    
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--<link href="{% static 'materialize/css/materialize.min.css' %}" rel="stylesheet">-->



      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=2.0"/>

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  
<body>




{% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
      <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
      {{ user.get_full_name|truncatechars:20 }}
      <span class="caret"></span>
        </a>
        
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}



 
   
       
           
          
        

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!--<script src="{% static 'materialize/js/materialize.min.js' %}"></script>-->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src=></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

my_proj/src/templates/contact.html
{% load staticifiles}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Contact Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="font-awesome/css/font-awesome.min.css" />

    <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

<div class="page-header">
    <h1>Contact Form <small>Bootstrap template, demonstrating a single contact form</small></h1>
</div>

<!-- Contact Form - START -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you within 2 business days." rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .header {
        color: #36A0FF;
        font-size: 27px;
        padding: 10px;
    }

    .bigicon {
        font-size: 35px;
        color: #36A0FF;
    }
</style>

<!-- Contact Form - END -->

</div>

</body>
</html>

my_proj/src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  
       <!--begin bg-carousel-->
<div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">
<!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slide1"  ><div class="col-md-8 col-sm-8">
         
          
	  
        </div></div>
        </div>
        <div class="item" >
            <div class="slide2"  ><div class="col-md-8 col-sm-8">
        
          
	  
        </div></div>
        </div>
        <div class="item" >
            <div class="slide3"  ><div class="col-md-8 col-sm-8">
          
          

        </div></div>
        </div>
        <div class="item">
            <div class="slide4" ><div class="col-md-8 col-sm-8">
          
          

        </div></div>
        </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay text-center">
        
       
        
    </div>
</div><!-- .carousel --> 
<!--end bg-carousel--> 
        
   
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <a href="{% url 'symptomchecker:symptomchecker' %}">
    <div class="col-lg-3">
      <h2>Symptom<b style="color:#069">Checker</b></h2>
      
    
      <img src="{% static 'site/img/symptom.jpeg' %}" alt="logo">
    
    </div>
  </a>
  <a href="{% url 'finddoctor:finddoctor' %}">
    <div class="col-lg-3">
      <h2>Find<b style="color:#069">Doctor</b></h2> 
      
     
       
      <img src="{% static 'site/img/doctor.jpeg' %}" alt="logo" href="#" style="PADDING-TOP: 10px" object-fit: contain>
     
    </div>
  </a>
  <a href="{% url 'medicinepredictor:medicinepredictor' %}">
    <div class="col-lg-3">
     <h2>Heart<b style="color:#069">Health</b></h2>
     
       
      <img src="{% static 'site/img/healthtip.png' %}" alt="logo" style="height: 70%; width: 70%; PADDING-TOP: 10px" object-fit: contain>
   
    </div>
  </a>
  <a href="{% url 'healthtips:healthtips' %}">
     <div class="col-lg-3">
      <h2>   Health<b style="color:#069">Tips</b></h2>
      
      <img src="{% static 'site/img/aboutus.jpg' %}" alt="logo" style="height: 70%; width: 70%; PADDING-TOP: 10px" object-fit: contain>
    
      
    </div>
  </a>
  </div>
</div>
<br> <br> <br>
<h2 style="PADDING-LEFT: 72px;PADDING-TOP: 40px">Health<b style="color:#069">News</b></h2><br> <br>
<div class="container">
  
  <div class="row">
   <div class="col-lg-4">
      <img src="{% static 'site/img/beepropolis.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Beauty and Skincare</h3>
      
      <p  style="text-align:justify">Did you know that honey isn’t the only thing that bees make? Bees also produce a compound called propolis from the sap on needle-leaved trees or evergreens. When they combine the sap with their own discharges and beeswax, they create a sticky, greenish-brown product that helps to fight disease and damage in the body.</p>
       
     
    </div>
    



   <div class="col-lg-4">
     
      <img src="{% static 'site/img/nsaid.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Healthy Heart</h3>
      
      <p style="text-align:justify">Could Prescribed NSAID Painkillers Raise Heart Failure Risk? Yes, say reports.Use of prescription-strength ibuprofen, naproxen and other commonly used pain relievers may lead to higher risk of heart failure.These medications may raise a person's relative risk of heart failure by 20%, according to the analysis of medical records for 10 million patients.</p>
       
     
    </div>
     <div class="col-lg-4">
      <img src="{% static 'site/img/essentialoil.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Depression</h3>
      
      <p style="text-align:justify">Depression can affect the way you feel, how you think, and the way you act.People use essential oils as complementary treatments for many conditions, including depression.These a drug-free option that may help relieve some of the symptoms and help manage the condition. In most cases, essential oils are safe and free of side effects.</p>
       
     
    </div>

  </div>
  <div class="row">
  


   <div class="col-lg-4">
      
      <img src="{% static 'site/img/flaxseed.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Cancer</h3>
      
      <p style="text-align:justify" >Flaxseed consumption may reduce the risk of prostate cancer.These are a rich source of nutrients, such as manganese, vitamin B-1, and omega-3 fatty acids.Although researchers are still exploring the potential health benefits of flaxseed, it is proven that falxseed protects us against a number of conditions ranging from diabetes to cancer.</p>
       
     
    </div>
     <div class="col-lg-4">
      
      <img src="{% static 'site/img/fodmap.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Food and Nutrition</h3>
      
      <p style="text-align:justify">Following a low-FODMAP diet can feel restrictive. Picks for low-FODMAP fiber sources include chia seeds, rolled oats, oat bran, white potatoes with skin, navel oranges, strawberries, blueberries, raspberries and quinoa. Hydration is also very important for people with digestive issues such as IBS.</p>
       
     
    </div>
     <div class="col-lg-4">
      
      <img src="{% static 'site/img/diabetes.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Diabetes</h3>
      
      <p style="text-align:justify">Glycemic index values of the same food can vary widely and may be an unreliable indicator of blood sugar response, according to a new study. Glycemic index is considered a tool to help people with diabetes control their blood sugar levels. Based on these findings, it was proven that the glycemic index wasn't practical for food labeling. </p>
       
     
    </div>
  </div>

  <div class="row">
   <div class="col-lg-4">
      
      <img src="{% static 'site/img/pregnancy.jpg' %}" alt="logo" style="width: 100%;height: 240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Pregnancy</h3>
      
      <p style="text-align:justify"> Regular exercise during pregnancy can improve heart health and stamina. Maintaining a healthy body and healthy weight gain can help reduce common pregnancy complaints and discomforts like lower back pain, fatigue and constipation and may even help make labor a little easier by improving endurance.</p>
       
     
    </div>



   <div class="col-lg-4">
      
      <img src="{% static 'site/img/sarsaparillaflowers.jpg' %}" alt="logo" style="width: 100%;height:240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Natural Therapy</h3>
      
      <p style="text-align:justify">Sarsaparilla is a tropical plant which grows deep in the canopy of the rainforest. For centuries,people around the world used the root of this plant for treating joint problems like arthritis, and for healing skin problems like psoriasis, eczema, and dermatitis.It was also thought to cure leprosy due to its “blood-purifying” properties.</p>
       
     
    </div>
     <div class="col-lg-4">
      
      <img src="{% static 'site/img/allergy.jpg' %}" alt="logo" style="width: 100%;height:240px;PADDING-TOP: 10px" object-fit: contain>
      <h3 style="color:#069" style="font-family:Lobster">Allergies</h3>
      
      <p style="text-align:justify">Good News! We can treat coughs due to colds, allergies, and other sinus infections with a number of home remedies that can help. For those who prefer to avoid chemicals, always keep one of these honey, probiotics, bromelain, peppermint, thyme handy to prevent getting affected by allergies. </p>
       
     
    </div>
  </div>
</div>  

{% endblock container %}






    

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}